fixed vtol vehicle status
PX4/px4_msgs pull request #23
Opened 2023-02-20 06:42 UTC by drasgo

fixed vtol vehicle status  to be consistent with what is being outputt…ed by px4 firmware

2023-02-20 08:01 UTC, sfuhrer requested changes
I don't understand the motivation behind this PR. Where do you need those fields? And the info in vtol_in_rw_mode, vtol_in_trans_mode, in_transition_to_fw is all duplication from what's already in vehicle_vtol_state.
Also, does it make sense to divert here from the original PX4 messages? From what I see in the readme they shouldn't be manually changed..

>When uORB message definitions in the [PX4 firmware](https://github.com/PX4/Firmware) repository change, a CI/CD pipeline automatically generates and pushes updated ROS message definitions to this repository. The ROS message definitions are generated by the [uorb_to_ros_msgs.py](https://github.com/PX4/Firmware/blob/master/msg/tools/uorb_to_ros_msgs.py) script. One can also use this script to generate its own ROS message definitions for new or modified uORB messages.

2023-03-07 05:47 UTC, drasgo commented
The reason for this pull request is that in the latest stable release of  PX4 Autopilot (1.13.2 https://github.com/PX4/PX4-Autopilot/tree/v1.13.2 ) some messages are inconsistent with the messages present in this repo. I understand there is the automated bot that automatically updates the messages here to mirror the messages in PX4, but this is true only for the main branch, and not for the stable releases, so I would suggest to either have here a branch for each stable release of PX4 Autopilot. The only branch I saw here is representing the messages as they were 4 years ago, so

2023-03-08 21:42 UTC, hamishwillee commented
PX4_msgs needs to be consistent with the associated release branch in order to allow PX4 and ROS to interwork. If you're working on PX4 main then these messages need to match the ones in the PX4 main branch. If you're working in PX4 v1.13 then the messages need to match the ones in the https://github.com/PX4/px4_msgs/tree/release/1.13 branch.

It is OK for PX4 v1.13 and PX4 main to diverge.

So this is invalid, and you should be using https://github.com/PX4/px4_msgs/tree/release/1.13

What docs pointed you to use the main branch? They might be broken.

2023-03-08 21:43 UTC, hamishwillee commented
FYI @beniaminopozzan That's right isn't it ^^^^ ?

PS @drasgo CI is supposed to automatically copy the messages across from PX4-Autopilot main, so even if you do this, it will get swamped by the next updates.

2023-03-08 23:34 UTC, beniaminopozzan commented
@hamishwillee thanks!
Yes, that is correct!

@drasgo , all the `1.13.x` tags have the same message definitions as the `.x`s are patches, major bugfix or new boards support.

>The only branch I saw here maybe doing this is release/1.13, but it is I am not sure to which sub-release this points to.

So, you can use `release/1.13` of this repo with any `1.13.x` of PX4-Autopilot

2023-03-08 23:34 UTC, closed without merging

2023-03-13 12:47 UTC, drasgo commented
Ah thank you! I'll use the `release/1.13` tag then, cheers!